server {
    listen 80;
    server_name filouche-app.ddns.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name filouche-app.ddns.net;

    ssl_certificate /etc/letsencrypt/live/filouche-app.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/filouche-app.ddns.net/privkey.pem;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}